import js from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginQuery from "@tanstack/eslint-plugin-query";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";

// One flat config for every TS workspace (web, ai, shared). The Python API
// has its own tooling and is ignored here.
export default tseslint.config(
  {
    ignores: [
      "**/dist/",
      "**/.next/",
      "**/node_modules/",
      "apps/api/",
      // Generated by `next dev`; Next.js owns its contents.
      "apps/ai/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  tseslint.configs.recommended,
  pluginQuery.configs["flat/recommended"],
  {
    files: ["**/*.{ts,tsx,mjs}"],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },
  {
    files: ["**/*.tsx"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  {
    // Vite HMR only swaps a module cleanly when components are its sole
    // exports; ui/ is exempt because shadcn primitives export cva recipes.
    files: ["apps/web/src/**/*.tsx"],
    ignores: ["apps/web/src/components/ui/**"],
    plugins: { "react-refresh": reactRefresh },
    rules: {
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
    },
  },
);
