"""initial schema

Revision ID: 60c3336077e8
Revises: 
Create Date: 2026-08-17 16:47:44.474533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c3336077e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_notes', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('saved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('completed', sa.Date(), nullable=True),
    sa.CheckConstraint("(status = 'Done') = (completed IS NOT NULL)", name='ck_action_items_completed_iff_done'),
    sa.CheckConstraint("priority IN ('High', 'Medium', 'Low')", name='ck_action_items_priority'),
    sa.CheckConstraint("status IN ('Not started', 'In progress', 'Blocked', 'Done')", name='ck_action_items_status'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_items')
    op.drop_table('meetings')
    op.drop_table('users')
    # ### end Alembic commands ###
